apiVersion: apps/v1
kind: Deployment
metadata:
  name: ugr-3361-13
  annotations:
    submitted-by: yohannes-bekele-ugr3361
  labels:
    app: mywebapp
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
      tier: frontend
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: devopsjourney1/mywebapp
        ports:
        - containerPort: 80